FROM arm32v7/ubuntu

LABEL maintainer="dexter.fryar@arm.com"

WORKDIR /root

# Install common utilities
RUN apt update && apt install -y --force-yes \
      python \
      python-pip \
      vim \
      most \
      tree \
      git \
      curl \
      wget \
      unzip \
      jq \
      srecord \
      moreutils

# Need this to get add-apt-repository
RUN apt install -y --force-yes software-properties-common

# Install mbed specific dependencies
RUN apt install -y --force-yes \
      mercurial \
      libssl-dev \
      libperl-dev \
      libgtk2.0-dev \
      cmake \
      bluez \
      gcc-arm-none-eabi

# Install mbed tools via pip package manager
RUN pip install \
      mbed-cli \
      click

# https://github.com/bbcmicrobit/micropython/issues/514
# arm-none-eabi/lib/crt0.o: Conflicting CPU architectures 13/1

RUN wget http://mirrors.kernel.org/ubuntu/pool/universe/n/newlib/libnewlib-arm-none-eabi_3.0.0.20180802-2_all.deb

RUN wget http://mirrors.kernel.org/ubuntu/pool/universe/n/newlib/libnewlib-dev_3.0.0.20180802-2_all.deb

RUN dpkg -i libnewlib-arm-none-eabi_3.0.0.20180802-2_all.deb libnewlib-dev_3.0.0.20180802-2_all.deb

WORKDIR /
