version: "3.3"
services:
  mbed_os_dev:
      command: ['/bin/bash']
      image: raspbian_dev
      build:
        context: .
        labels:
          com.mbed.os.description: "Build enviroment for Mbed OS on Rasbian"
        dockerfile: Dockerfile.raspbian_dev
